### ISSUE TITLE
[US09] - Eu como usuário, desejo que todo o frontend de autenticação do sistema esteja pronto.

### ISSUE THREAD

**Issue by VictorArnaud** [TeamBasedLearning/Service#17]
Critérios de aceitação:

- [x] Login no sistema
- [x] Registro no sistema
- [x] Página de perfil
- [x] Página para editar informações
- [x] Página para deletar conta
- [x] Página para Notificações
